[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

lexer = { path = "../lexer" }